### ISSUE TITLE
NameError: name 'self' is not defined

### ISSUE THREAD

**Issue by gsramsu** [shawnwun/RNNLG#5]
Hi,

I cloned the RNNLG repository and am trying to train an SCLSTM. When I ran the code, I got an error in the in net.py in the saveNet() function -- name 'self' not defined. Am unable to figure this out, as self has been passed as an argument to the function, so it shouldn't exit with an error at this point. Could you please help me out?

**Comment by bonkyzhu** [comment]
I came across this issue too. Could you tell me how to figure out this problem? Appreciating for your help :-)
